# Generated by Django 5.0.1 on 2024-01-28 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoshop', '0003_menubutton_alter_banner_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(auto_created=True, default=True, verbose_name='Активность')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название')),
                ('old_price', models.IntegerField(blank=True, max_length=10, null=True, verbose_name='Старая цена')),
                ('new_price', models.IntegerField(blank=True, max_length=10, null=True, verbose_name='Новая цена')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Баннер')),
            ],
        ),
        migrations.DeleteModel(
            name='MenuButton',
        ),
    ]
