# Generated by Django 5.0.1 on 2024-01-28 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoshop', '0006_creditprogram_alter_creditinfo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creditprogram',
            options={'verbose_name': 'Программа рассрочки', 'verbose_name_plural': 'Программы рассрочки'},
        ),
    ]
