# Generated by Django 5.0.1 on 2024-01-28 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoshop', '0007_alter_creditprogram_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditinfo',
            name='programm',
            field=models.ManyToManyField(blank=True, null=True, to='demoshop.creditprogram'),
        ),
    ]
