# Generated by Django 5.0.1 on 2024-01-26 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(auto_created=True, default=True, verbose_name='Активность')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Баннер 1920х400px')),
                ('url', models.CharField(blank=True, max_length=500, null=True, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры',
            },
        ),
    ]
