# Generated by Django 5.0.1 on 2024-01-27 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoshop', '0002_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(auto_created=True, default=True, verbose_name='Активность')),
                ('title', models.CharField(max_length=20, verbose_name='Наименование')),
                ('url', models.CharField(blank=True, max_length=500, null=True, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Кнопка',
                'verbose_name_plural': 'Меню',
            },
        ),
        migrations.AlterField(
            model_name='banner',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Баннер'),
        ),
    ]
