# Generated by Django 5.0.1 on 2024-01-28 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoshop', '0005_creditinfo_alter_promoblock_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название')),
                ('vznos', models.IntegerField(blank=True, max_length=10, null=True, verbose_name='Первый взнос')),
                ('overprice', models.IntegerField(blank=True, max_length=10, null=True, verbose_name='Переплата')),
                ('lengh', models.IntegerField(blank=True, max_length=10, null=True, verbose_name='Срок кредита')),
            ],
        ),
        migrations.AlterModelOptions(
            name='creditinfo',
            options={'verbose_name': 'Рассрочка', 'verbose_name_plural': 'Информация о рассрочке'},
        ),
        migrations.RemoveField(
            model_name='creditinfo',
            name='my_field',
        ),
        migrations.AddField(
            model_name='creditinfo',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название'),
        ),
    ]
