# Generated by Django 4.2.10 on 2024-02-24 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demoshop', '0011_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditinfo',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Программа+', to='demoshop.creditprogram'),
        ),
    ]
