# Generated by Django 4.2.10 on 2024-02-24 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demoshop', '0012_creditinfo_child'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditinfo',
            name='child',
        ),
        migrations.RemoveField(
            model_name='creditinfo',
            name='programm',
        ),
        migrations.AddField(
            model_name='creditprogram',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Родитель+', to='demoshop.creditinfo'),
        ),
    ]
