# Generated by Django 4.2.10 on 2024-02-24 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoshop', '0013_remove_creditinfo_child_remove_creditinfo_programm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, null=True, verbose_name='Номер телефона')),
                ('telega', models.CharField(max_length=200, null=True, verbose_name='Telegram')),
                ('whatsapp', models.CharField(max_length=200, null=True, verbose_name='Whatsapp')),
                ('insta', models.CharField(max_length=200, null=True, verbose_name='Instagramm')),
            ],
        ),
    ]
