# Generated by Django 4.2.10 on 2024-02-24 08:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoshop', '0015_products_delete_task_alter_contactinfo_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='memory',
            field=models.CharField(blank=True, default='', max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(0)], verbose_name='Объем памяти ГБ'),
        ),
    ]
