# Generated by Django 4.2.10 on 2024-02-24 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoshop', '0016_products_memory'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagsShild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='tags',
            field=models.CharField(blank=True, choices=[('Новинка', 'Новинка 1'), ('Рассрочка', 'Рассрочка 2'), ('Акция', 'Акция 3')], max_length=100, null=True, verbose_name='Шильдик'),
        ),
    ]
