# Generated by Django 4.2.10 on 2024-02-24 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demoshop', '0017_tagsshild_products_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Родительский элемент+', to='demoshop.subcategory', verbose_name='Родительская категория'),
        ),
    ]
