# Generated by Django 4.2.10 on 2024-02-24 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoshop', '0018_alter_products_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='', verbose_name='image')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='products',
            name='image_detail',
            field=models.ManyToManyField(blank=True, to='demoshop.publication'),
        ),
    ]
