# Generated by Django 4.2.10 on 2024-02-24 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoshop', '0019_publication_products_image_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='image_detail',
        ),
        migrations.DeleteModel(
            name='Publication',
        ),
    ]
