# Generated by Django 5.0.2 on 2024-02-25 19:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoshop', '0021_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='count',
            field=models.IntegerField(default='0', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)], verbose_name='Доступное количество'),
        ),
        migrations.AddField(
            model_name='products',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активность'),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demoshop.subcategory', verbose_name='Родительская категория'),
        ),
        migrations.AlterField(
            model_name='products',
            name='memory',
            field=models.CharField(blank=True, default='', max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(0)], verbose_name='Объем памяти'),
        ),
        migrations.AlterField(
            model_name='products',
            name='tags',
            field=models.CharField(blank=True, choices=[('Новинка', 'Новинка'), ('Рассрочка', 'Рассрочка'), ('Акция', 'Акция')], max_length=100, null=True, verbose_name='Шильдик'),
        ),
    ]
