# Generated by Django 5.0.2 on 2024-02-25 19:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoshop', '0022_products_count_products_is_active_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PromoBlock',
        ),
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['sort'], 'verbose_name': 'Баннер', 'verbose_name_plural': 'Баннеры'},
        ),
        migrations.AddField(
            model_name='banner',
            name='sort',
            field=models.IntegerField(blank=True, default=500, null=True, verbose_name='Сортировка'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='products',
            name='date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='products',
            name='old_price',
            field=models.FloatField(default=0, verbose_name='Старая цена'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Ссылка на внешний ресурс'),
        ),
        migrations.AlterField(
            model_name='products',
            name='count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)], verbose_name='Доступное количество'),
        ),
    ]
