# Generated by Django 5.0.2 on 2024-02-26 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoshop', '0023_delete_promoblock_alter_banner_options_banner_sort_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='img')),
            ],
        ),
        migrations.CreateModel(
            name='TestModel2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ManyToManyField(to='demoshop.testmodel', verbose_name='imgs')),
            ],
        ),
    ]
