# Generated by Django 5.0.2 on 2024-02-26 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoshop', '0024_testmodel_testmodel2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testmodel2',
            name='images',
        ),
        migrations.DeleteModel(
            name='TestModel',
        ),
        migrations.DeleteModel(
            name='TestModel2',
        ),
    ]
